server:
  port: 8081
spring:
  resource:
    staticLocations: classpath:/static/,classpath:/public/
  main:
    exclude: org.springframework.boot.autoconfigure.logging.*
    allow-bean-definition-overriding: true
    #  数据库配置
  datasource:
    hikari:
      idleTimeout: 300000
      maxLifetime: 600000
      maximumPoolSize: 50
      minimumIdle: 5
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/flowable-spring-boot?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&nullCatalogMeansCurrent=true
    username: root
    password: yurun123#

# flowable 配置
# 关闭异步，不关闭历史数据的插入就是异步的，会在同一个事物里面，无法回滚
# 开发可开启会提高些效率，上线需要关闭
flowable:
  async-executor-activate: false
  common:
    app:
      #      目前先设置一个正确但是不一定可用的url地址
      idm-url: http://localhost:8080/flowable-idm1
      idm-admin:
        #        需要设置一个密码，目前先设置，后期不使用
        password: test
        #        默认user为admin，这个地方可设置可不设置
        user: admin1

mybatis:
  # 新增 modeler-mybatis-mappings xml 扫描
  mapper-locations: mapper/*/*.xml, classpath*:mapper/*.xml, classpath:/META-INF/modeler-mybatis-mappings/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 参数配置
  configuration-properties:
    # 配置流程引擎参数，详情可见 DatabaseConfiguration
    blobType: BLOB
    boolValue: TRUE
    # 不要设置库名，否则会出现双库名 bug
    prefix: ''
